version: '3.1'

networks:
  app-network:
    driver: bridge
volumes:
  rabbitmq_data:

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Default RabbitMQ port
      - "15672:15672" # Management UI port
    env_file:
      - docker.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist data
      - ./rabbitmq-init.sh:/etc/docker-entrypoint.d/01-create-queue.sh  # Mount initialization script
